In [2]:
import numpy as np
list_ = [ 1 , 2 , 3 , 4 , 5 ]
array_list = np.array(object = list_)

In [3]:
list_ = [ 1 , 2 , 3 , 4 , 5 ]

array_list = np.array(object = list_)

print(type(list_))
print(array_list)

<class 'list'>
[1 2 3 4 5]


In [4]:
list_ = [ 1 , 2 , 3 , 4 , 5 ]

array_list = np.array(object = list_)

for i in range(len(list_)):
    
    print(f"The data type of element {i} in list_ is {type(list_[i])}")
    
for i in range(len(array_list)):
    
    print(f"The data type of element {i} in list_ is {type(array_list[i])}")
    

The data type of element 0 in list_ is <class 'int'>
The data type of element 1 in list_ is <class 'int'>
The data type of element 2 in list_ is <class 'int'>
The data type of element 3 in list_ is <class 'int'>
The data type of element 4 in list_ is <class 'int'>
The data type of element 0 in list_ is <class 'numpy.int32'>
The data type of element 1 in list_ is <class 'numpy.int32'>
The data type of element 2 in list_ is <class 'numpy.int32'>
The data type of element 3 in list_ is <class 'numpy.int32'>
The data type of element 4 in list_ is <class 'numpy.int32'>


In [8]:
import numpy as np

list_ = [1, 2, 3, 4, 5]
array_list = np.array(object=list_, dtype=int)

for i in range(len(list_)):
    print(f"The data type of element {i} in list_ is {type(list_[i])}")

for i in range(len(array_list)):
    print(f"The data type of element {i} in array_list is {type(array_list[i])}")

The data type of element 0 in list_ is <class 'int'>
The data type of element 1 in list_ is <class 'int'>
The data type of element 2 in list_ is <class 'int'>
The data type of element 3 in list_ is <class 'int'>
The data type of element 4 in list_ is <class 'int'>
The data type of element 0 in array_list is <class 'numpy.int32'>
The data type of element 1 in array_list is <class 'numpy.int32'>
The data type of element 2 in array_list is <class 'numpy.int32'>
The data type of element 3 in array_list is <class 'numpy.int32'>
The data type of element 4 in array_list is <class 'numpy.int32'>


In [7]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

for i in range(len(num_list)):
    
    for j in range(len(num_list[i])):
        
        print(f"The data type of element ({i}, {j}) in num_list is {type(num_list[i][j])}")
        
        
for i in range(num_array.shape[0]):
    
    for j in range(num_array.shape[1]):
        
        print(f"The data type of element ({i}, {j}) in num_array is {type(num_array[i][j])}")

The data type of element (0, 0) in num_list is <class 'int'>
The data type of element (0, 1) in num_list is <class 'int'>
The data type of element (0, 2) in num_list is <class 'int'>
The data type of element (1, 0) in num_list is <class 'int'>
The data type of element (1, 1) in num_list is <class 'int'>
The data type of element (1, 2) in num_list is <class 'int'>
The data type of element (0, 0) in num_array is <class 'numpy.int32'>
The data type of element (0, 1) in num_array is <class 'numpy.int32'>
The data type of element (0, 2) in num_array is <class 'numpy.int32'>
The data type of element (1, 0) in num_array is <class 'numpy.int32'>
The data type of element (1, 1) in num_array is <class 'numpy.int32'>
The data type of element (1, 2) in num_array is <class 'numpy.int32'>


In [9]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)


print(f"The shape of num_array is {num_array.shape}")


print(f"The size of num_array is {num_array.size}")

The shape of num_array is (2, 3)
The size of num_array is 6


In [10]:
import numpy as np

zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as np

identity_matrix = np.identity(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
