### Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its application.

In [5]:
import numpy as np

original_scores = np.array([60, 75, 80, 90, 95])

_min = np.min(original_scores)
X_max = np.max(original_scores)

scaled_scores = (original_scores - X_min) / (X_max - X_min)

print("Min-Max scaling:",scaled_scores)

Min-Max scaling: [0.         0.42857143 0.57142857 0.85714286 1.        ]


In [8]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

original_scores = np.array([60, 75, 80, 90, 95])

reshaped_scores = original_scores.reshape(-1, 1)

min_max=MinMaxScaler()

min_max.fit(reshaped_scores)

min_max.transform(reshaped_scores)

array([[0.        ],
       [0.42857143],
       [0.57142857],
       [0.85714286],
       [1.        ]])

### Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling? Provide an example to illustrate its application.

In [10]:
import seaborn as sns

df=sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
from sklearn.preprocessing import normalize

import pandas as pd

pd.DataFrame(normalize(df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]),
             columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])

sepal_length  sepal_width  petal_length  petal_width
0        0.803773     0.551609      0.220644     0.031521
1        0.828133     0.507020      0.236609     0.033801
2        0.805333     0.548312      0.222752     0.034269
3        0.800030     0.539151      0.260879     0.034784
4        0.790965     0.569495      0.221470     0.031639
..            ...          ...           ...          ...
145      0.721557     0.323085      0.560015     0.247699
146      0.729654     0.289545      0.579090     0.220054
147      0.716539     0.330710      0.573231     0.220474
148      0.674671     0.369981      0.587616     0.250281
149      0.690259     0.350979      0.596665     0.210588

[150 rows x 4 columns]

### Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an example to illustrate its application.

In [14]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn import datasets
from sklearn.model_selection import train_test_split


dataset=datasets.load_iris()

X=dataset['data']
y=dataset['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## PCA- Transformation
pca=PCA(n_components=3)
pca

X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)


print(pca.components_)

print(pca.explained_variance_ratio_)


[[ 0.36873621 -0.06977632  0.85630117  0.35484246]
 [ 0.68187006  0.69682861 -0.1867726  -0.12082672]
 [-0.53692993  0.63566209  0.05426774  0.55199182]]
[0.9201008  0.05494812 0.01978256]


### Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature Extraction? Provide an example to illustrate this concept.

In [17]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn import datasets
from sklearn.model_selection import train_test_split


dataset=datasets.load_iris()

X=dataset['data']
y=dataset['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## PCA- Transformation
pca=PCA(n_components=2)
pca

X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)


print(pca.components_)

print(pca.explained_variance_ratio_)


[[ 0.36873621 -0.06977632  0.85630117  0.35484246]
 [ 0.68187006  0.69682861 -0.1867726  -0.12082672]]
[0.9201008  0.05494812]


### Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to preprocess the data.

In [18]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

data = {'price': [10, 20, 30, 15],
        'rating': [4.5, 3.2, 4.8, 3.9],
        'delivery_time': [30, 45, 25, 40]}

df = pd.DataFrame(data)

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)

df_scaled = pd.DataFrame(scaled_data, columns=df.columns)

print(df_scaled)


   price  rating  delivery_time
0   0.00  0.8125           0.25
1   0.50  0.0000           1.00
2   1.00  1.0000           0.00
3   0.25  0.4375           0.75


### Q6. You are working on a project to build a model to predict stock prices. The dataset contains many features, such as company financial data and market trends. Explain how you would use PCA to reduce the dimensionality of the dataset.

In [39]:
import pandas as pd
import numpy as np

data = {
    'stock_price': [100, 110, 120, 130, 140],
    'revenue': [100000, 120000, 150000, 180000, 200000],
    'profit': [20000, 25000, 30000, 35000, 40000],
    'debt': [50000, 40000, 30000, 20000, 10000],
    'market_trend_1': [0.1, 0.2, 0.3, 0.4, 0.5],
    'market_trend_2': [0.5, 0.4, 0.3, 0.2, 0.1]
}

df = pd.DataFrame(data)

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

X = df.drop('stock_price', axis=1)
y = df['stock_price']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)  
X_pca = pca.fit_transform(X_scaled)

print(X_pca)


[[ 3.13619740e+00  5.00117142e-02]
 [ 1.62864670e+00 -9.63048695e-02]
 [-3.51654987e-20 -4.96506706e-17]
 [-1.62864670e+00  9.63048695e-02]
 [-3.13619740e+00 -5.00117142e-02]]


### Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the values to a range of -1 to 1.

In [29]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

original_scores = np.array([1, 5, 10, 15, 20])

reshaped_scores = original_scores.reshape(-1, 1)

min_max = MinMaxScaler(feature_range=(-1, 1))

scaled_scores = min_max.fit_transform(reshaped_scores)

print(scaled_scores.flatten())


[-1.         -0.57894737 -0.05263158  0.47368421  1.        ]


### Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform Feature Extraction using PCA. How many principal components would you choose to retain, and why?

In [34]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Prepare the dataset
data = {
    'height': [170, 165, 180, 155, 175],
    'weight': [65, 55, 70, 45, 68],
    'age': [30, 25, 35, 28, 32],
    'gender': [0, 1, 1, 0, 1],
    'blood_pressure': [120, 118, 122, 115, 123]
}

df = pd.DataFrame(data)

features = df[['height', 'weight', 'age', 'gender', 'blood_pressure']]

scaler = StandardScaler()
scaled_data = scaler.fit_transform(features)

pca = PCA()
pca.fit(scaled_data)

explained_variance_ratio = pca.explained_variance_ratio_

# Determine the number of principal components to retain
cumulative_variance_ratio = np.cumsum(explained_variance_ratio)

num_components = np.argmax(cumulative_variance_ratio >= 0.95) + 1

print("Explained Variance Ratio:", explained_variance_ratio)
print("Cumulative Variance Ratio:", cumulative_variance_ratio)
print("Number of Principal Components to Retain:", num_components)


Explained Variance Ratio: [7.86997282e-01 1.56971400e-01 4.76276032e-02 8.40371432e-03
 1.81905527e-33]
Cumulative Variance Ratio: [0.78699728 0.94396868 0.99159629 1.         1.        ]
Number of Principal Components to Retain: 3
